image: $CI_REGISTRY/docker/php7.4-xdebug-apache

stages:
    - test
    - deploy

variables:
  # symfony 4
  http_proxy: $CI_HTTP_PROXY
  https_proxy: $CI_HTTPS_PROXY
  ftp_proxy: $CI_FTP_PROXY
  no_proxy: $CI_NO_PROXY
  https_proxy_request_fulluri: 0
  HTTP_PROXY: $CI_HTTP_PROXY
  HTTPS_PROXY: $CI_HTTPS_PROXY
  FTP_PROXY: $CI_FTP_PROXY
  NO_PROXY: $CI_NO_PROXY
  HTTPS_PROXY_REQUEST_FULLURI: 0
  NSS_SSL_CBC_RANDOM_IV: 0
  DATABASE_URL: $CI_TEST_DB_URL
  BICORE_SCHEMA: $CI_TARGET_DB_SCHEMA
  POSTGRES_DB: divodb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: "adminpass"

cache:
  paths:
  - vendor/

before_script:
      - mkdir ~/.ssh
      - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client  -y )'
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - chmod 700 ~/.ssh
      - chmod 644 ~/.ssh/known_hosts
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\tLogLevel=quiet\n\n" > ~/.ssh/config
      - echo $HTTP_PROXY
      - echo $http_proxy
      - echo $CI_COMMIT_TAG
      - echo $TESTAPPENVS;
      - ls -al
      - composer install --no-interaction
      - bin/console bicorebundle:install admin adminpass admin@admin.it
      - bin/console App:CreateViews
      - bin/console App:LoadFixtures
test:
    only:
      refs:
        - develop
    stage: test
    services:
      - postgres:12.2-alpine
    script:
      - bin/simple-phpunit
deploy:
    only:
      refs:
        - tags
    stage: deploy
    script:
      - bin/console deploy test -v
