checks:
    php:
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        optional_parameters_at_the_end: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: '3'
        no_long_variable_names:
            maximum: '20'
        no_goto: true
        newline_at_end_of_file: true
        more_specific_types_in_doc_comments: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_multiple_statements_on_same_line: true
        align_assignments: true
        code_rating: true
            
build:
    environment:
        php:
            version: 7.4  # or any other released version
            ini:
                'memory_limit': '4G'
        node: "v10.15.3"
        variables:
          DATABASE_URL: pgsql://scrutinizer:scrutinizer@127.0.0.1:5432/scrutinizer
        postgresql: true
    services:
        postgres: 12
        
    nodes:
      analysis:
        tests:
          override:
            - 'composer install --no-interaction --no-scripts'
            - 'bin/console bicorebundle:install admin password admin@admin.it'
            - 'bin/console App:CreateViews'
            - 'bin/console App:LoadFixtures'
            - 'php-scrutinizer-run'
            
      tests:
          environment:
              php: 7.4
          dependencies:
              override:
                  - 'composer install --no-interaction --no-scripts'
                  - 'bin/console bicorebundle:install admin password admin@admin.it'
                  - 'bin/console App:CreateViews'
                  - 'bin/console App:LoadFixtures'
          tests:
              override:
                  - on_node: 2
                    idle_timeout: 4800
                    command: "./bin/simple-phpunit"
            
filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
    paths:
        - 'src/*'
tools:
    #external_code_coverage:
    #    timeout: 3600    # Timeout in seconds.
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["build", "tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["build", "tests", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["build", "tests", "vendor"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["src/*", "tests/*"]
    sensiolabs_security_checker: true
    